from __future__ import absolute_import

from .resnet_new3_sigmoid import new3_sigmoid_resnet18
from .resnet_new1_ablation import new1_ablation_resnet18
from .resnet_identical4 import identical4_resnet18
from .resnet_identical4B import identical4B_resnet18
